### ISSUE TITLE
FATAL Could not parse modules: No modules provided

### ISSUE THREAD

**Issue by rogchap** [fossa-contrib/fossa-action#90]
Tried to use this action and failed instantly:

```

Run fossa-contrib/fossa-action@v1
  with:
    fossa-api-key: ***
    github-token: ***
    skip-test: true
  env:
    GOROOT: /Users/runner/hostedtoolcache/go/1.12.17/x64
/usr/bin/tar xz -C /Users/runner/work/_temp/7d29c9ab-3897-45e0-8692-9c8aff6ccbe4 -f /Users/runner/work/_temp/130d8735-53d8-4807-9e50-04711814f2cc
/Users/runner/hostedtoolcache/fossa-cli/1.1.3/darwin_amd64/fossa init
INFO Initializing...
/Users/runner/hostedtoolcache/fossa-cli/1.1.3/darwin_amd64/fossa analyze
FATAL Could not parse modules: No modules provided
(node:1906) UnhandledPromiseRejectionWarning: Error: The process '/Users/runner/hostedtoolcache/fossa-cli/1.1.3/darwin_amd64/fossa' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_actions/fossa-contrib/fossa-action/v1/dist/index.js:866:19)
    at ExecState.CheckComplete (/Users/runner/work/_actions/fossa-contrib/fossa-action/v1/dist/index.js:852:14)
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/fossa-contrib/fossa-action/v1/dist/index.js:755:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
(node:1906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1906) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by smorimoto** [comment]
If you use it with a particular Go version, you may need to include these steps. ​Have you tried it?
https://github.com/fluxcd/flux2/blob/afe0ddcd8400532da5225bb0efc1fc9002c9db42/.github/workflows/fossa.yml#L16-L19

**Comment by smorimoto** [comment]
The error is not as reader-friendly as we'd expect, but it's probably not a problem with the action itself.
At least that error is from fossa-cli: https://github.com/fossas/fossa-cli/blob/fc60c6631a5d372d5a45fea35e31665b338f260d/cmd/fossa/cmd/analyze/analyze.go#L243

**Comment by smorimoto** [comment]
The error message is improved in the latest release.

**Comment by rogchap** [comment]
Thanks for your help @smorimoto 
I've managed to track down the issues thanks to your links.

**Comment by smorimoto** [comment]
I'm glad it solved! It's always a good idea to scan licenses. Feel free to ping me if you are stuck again :)

**Comment by smorimoto** [comment]
By the way, you can set `skip-test` to `false` to find out which code has licensing issues before merging them: https://github.com/fossa-contrib/fossa-action#inputs
